### PR TITLE
Some code blocks do not look good on github's readme view.

### PR DESCRIPTION
**Pull request by greg0ire**
Some code blocks do not look properly for the moment. In markdown code blocks works with spaces, not with tabs. I'm trying the other methods, which use a triple ` + the name of the language. It is supposed to offer syntax highlighting. Read about it here : http://github.github.com/github-flavored-markdown/

### CODE REVIEW

**Comment by greg0ire** [comment]
I got it to work eventually :P

**Comment by rande** [comment]
So it does not work

**Comment by greg0ire** [comment]
Of course it does! I said I got it to work (with this last commit https://github.com/greg0ire/SonataGoutteBundle/commit/af54ab56e9b31d290c37687426b3d60f5d4b2df5). It looks like all the commits, including this one, were added to the pull request, weren't they?

**Comment by greg0ire** [comment]
You can see how it looks on this page : https://github.com/greg0ire/SonataGoutteBundle/tree/patch-1

**Pull request merged**
